nedv/Models/Data/TypeOfConstruction.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace nedv.Models.Data
{
    public class TypeOfConstruction
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите тип постройки")]
        [Display(Name = "Тип постройки")]
        public string TypeOfConstructionName { get; set; }
    }
}

nedv/Controllers/AdTypesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using nedv.Models;
using nedv.Models.Data;
using nedv.ViewModel.AdTypes;

namespace nedv.Controllers
{
    public class AdTypesController : Controller
    {
        private readonly AppCtx _context;

        public AdTypesController(AppCtx context)
        {
            _context = context;
        }

        // GET: AdTypes
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var adtypes = from at in _context.AdTypes select at;

            if (!String.IsNullOrEmpty(searchString))
            {
                adtypes = adtypes.Where(s => s.AdTypeName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    adtypes = adtypes.OrderByDescending(at => at.AdTypeName);
                    break;
                default:
                    adtypes = adtypes.OrderBy(at => at.AdTypeName);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<AdType>.CreateAsync(adtypes.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: AdTypes/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.AdTypes == null)
            {
                return NotFound();
            }

            var adType = await _context.AdTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adType == null)
            {
                return NotFound();
            }

            return View(adType);
        }

        // GET: AdTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAdTypeViewModel model)
        {
            if (_context.AdTypes
                .Where(f => f.AdTypeName == model.AdTypeName)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеный тип объявления уже существует");
            }

            if (ModelState.IsValid)
            {
                AdType adtype = new()
                {
                    AdTypeName = model.AdTypeName
                };

                _context.Add(adtype);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: AdTypes/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.AdTypes == null)
            {
                return NotFound();
            }

            var adType = await _context.AdTypes.FindAsync(id);
            if (adType == null)
            {
                return NotFound();
            }

            EditAdTypeViewModel model = new()
            {
                Id = adType.Id,
                AdTypeName = adType.AdTypeName
            };
            return View(model);
        }

        // POST: AdTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditAdTypeViewModel model)
        {
            AdType adType = await _context.AdTypes.FindAsync(id);

            if (_context.AdTypes
               .Where(f => f.AdTypeName == model.AdTypeName)
               .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеный тип объявления уже существует");
            }

            if (id != adType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    adType.AdTypeName = model.AdTypeName;
                    _context.Update(adType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdTypeExists(adType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: AdTypes/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.AdTypes == null)
            {
                return NotFound();
            }

            var adType = await _context.AdTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adType == null)
            {
                return NotFound();
            }

            return View(adType);
        }

        // POST: AdTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.AdTypes == null)
            {
                return Problem("Entity set 'AppCtx.AdTypes'  is null.");
            }
            var adType = await _context.AdTypes.FindAsync(id);
            if (adType != null)
            {
                _context.AdTypes.Remove(adType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdTypeExists(short id)
        {
          return (_context.AdTypes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

nedv/Controllers/TypeOfConstructionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using nedv.Models;
using nedv.Models.Data;
using nedv.ViewModel.TypeOfConstructions;

namespace nedv.Controllers
{
    [Authorize(Roles = "admin")]
    public class TypeOfConstructionsController : Controller
    {
        private readonly AppCtx _context;

        public TypeOfConstructionsController(AppCtx context)
        {
            _context = context;
        }

        // GET: TypeOfConstructions
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["TypeOfConstructionSortParm"] = String.IsNullOrEmpty(sortOrder) ? "roomtypename_desc" : "";

            var typeofconstrucrion = from t in _context.TypeOfConstructions
                           select t;
            if (!String.IsNullOrEmpty(searchString))
            {
                typeofconstrucrion = typeofconstrucrion.Where(t => t.TypeOfConstructionName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    typeofconstrucrion = typeofconstrucrion.OrderByDescending(t => t.TypeOfConstructionName);
                    break;
                default:
                    typeofconstrucrion = typeofconstrucrion.OrderBy(t => t.TypeOfConstructionName);
                    break;
            }
            return View(await typeofconstrucrion.AsNoTracking().ToListAsync());
        }

        // GET: TypeOfConstructions/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.TypeOfConstructions == null)
            {
                return NotFound();
            }

            var typeOfConstruction = await _context.TypeOfConstructions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (typeOfConstruction == null)
            {
                return NotFound();
            }

            return View(typeOfConstruction);
        }

        // GET: TypeOfConstructions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TypeOfConstructions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTypeOfConstructionViewModel model)
        {
            if (_context.TypeOfConstructions
                .Where(f => f.TypeOfConstructionName == model.TypeOfConstructionName)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеный тип постройки уже существует");
            }

            if (ModelState.IsValid)
            {
                TypeOfConstruction typeOfConstruction = new()
                {
                    TypeOfConstructionName = model.TypeOfConstructionName
                };

                _context.Add(typeOfConstruction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: TypeOfConstructions/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.TypeOfConstructions == null)
            {
                return NotFound();
            }

            var typeOfConstruction = await _context.TypeOfConstructions.FindAsync(id);
            if (typeOfConstruction == null)
            {
                return NotFound();
            }

            EditTypeOfConstructionViewModel model = new()
            {
                Id = typeOfConstruction.Id,
                TypeOfConstructionName = typeOfConstruction.TypeOfConstructionName
            };
            return View(model);
        }

        // POST: TypeOfConstructions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditTypeOfConstructionViewModel model)
        {
            TypeOfConstruction typeOfConstruction = await _context.TypeOfConstructions.FindAsync(id);

            if (_context.TypeOfConstructions
               .Where(f => f.TypeOfConstructionName == model.TypeOfConstructionName)
               .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеный тип постройки уже существует");
            }

            if (id != typeOfConstruction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    typeOfConstruction.TypeOfConstructionName = model.TypeOfConstructionName;
                    _context.Update(typeOfConstruction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeOfConstructionExists(typeOfConstruction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: TypeOfConstructions/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.TypeOfConstructions == null)
            {
                return NotFound();
            }

            var typeOfConstruction = await _context.TypeOfConstructions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (typeOfConstruction == null)
            {
                return NotFound();
            }

            return View(typeOfConstruction);
        }

        // POST: TypeOfConstructions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.TypeOfConstructions == null)
            {
                return Problem("Entity set 'AppCtx.TypeOfConstruction'  is null.");
            }
            var typeOfConstruction = await _context.TypeOfConstructions.FindAsync(id);
            if (typeOfConstruction != null)
            {
                _context.TypeOfConstructions.Remove(typeOfConstruction);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TypeOfConstructionExists(short id)
        {
          return (_context.TypeOfConstructions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

nedv/Views/TypeOfConstructions/Create.cshtml
@model nedv.ViewModel.TypeOfConstructions.CreateTypeOfConstructionViewModel

@{
    ViewData["Title"] = "Добавление - типа постройки";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="AdTypes" asp-action="Index">Типы постройки</a></li>
        <li class="breadcrumb-item active">Добавление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление типа постройки
</h3>

<h4>Тип постройки</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="TypeOfConstructionName" class="control-label"></label>
                <input asp-for="TypeOfConstructionName" class="form-control" />
                <span asp-validation-for="TypeOfConstructionName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nedv/Views/TypeOfConstructions/Delete.cshtml
@model nedv.Models.Data.TypeOfConstruction

@{
    ViewData["Title"] = "Удаление - типа постройки";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="AdTypes" asp-action="Index">Типы постройки</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление типа постройки
</h3>

<h3>Вы уверены что хотите удалить?</h3>
<div>
    <h4>TypeOfConstruction</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfConstructionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfConstructionName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
    </form>
</div>

nedv/Views/TypeOfConstructions/Details.cshtml
@model nedv.Models.Data.TypeOfConstruction

@{
    ViewData["Title"] = "Детали - Типа постройки";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="AdTypes" asp-action="Index">Типы постройки</a></li>
        <li class="breadcrumb-item active">Детали</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Просмотр типа постройки
</h3>


<div>
    <h4>TypeOfConstruction</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfConstructionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfConstructionName)
        </dd>
    </dl>
</div>

nedv/Views/TypeOfConstructions/Edit.cshtml
@model nedv.ViewModel.TypeOfConstructions.EditTypeOfConstructionViewModel

@{
    ViewData["Title"] = "Изменение - типа постройки";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="AdTypes" asp-action="Index">Типы постройки</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение типа постройки
</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="mb-3">
                <label asp-for="TypeOfConstructionName" class="control-label"></label>
                <input asp-for="TypeOfConstructionName" class="form-control" />
                <span asp-validation-for="TypeOfConstructionName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nedv/Views/TypeOfConstructions/Index.cshtml
@model IEnumerable<nedv.Models.Data.TypeOfConstruction>

@{
    ViewData["Title"] = "Тип постройки";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item active">Типы постройки</li>
    </ol>
</nav>
<h2>Типы постройки</h2>

<h6>
    <a class="btn text-dark" asp-action="Create">
        <i class="far fa-plus-square"></i>  Добавить тип постройки
    </a>
</h6>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Поиск по названию: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Поиск" class="btn btn-default" /> |
            <a asp-action="Index">Вернуться к списку</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.TypeOfConstructionName)</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfConstructionName)
            </td>
            <td>
                    <a class="btn text-dark" asp-action="Details" asp-route-id="@item.Id" title="Посмотреть подробнее">
                        <i class="far fa-eye"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Edit" asp-route-id="@item.Id" title="Редактировать">
                        <i class="fas fa-pencil-alt"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Delete" asp-route-id="@item.Id" title="Удалить">
                        <i class="far fa-minus-square"></i>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>