nedv/Models/Data/Region.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace nedv.Models.Data
{
    public class Region
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите область")]
        [Display(Name = "Область")]
        public string RegionName { get; set; }
    }
}

nedv/Controllers/RegionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using nedv.Models;
using nedv.Models.Data;
using nedv.ViewModel.Cities;
using nedv.ViewModel.Regions;

namespace nedv.Controllers
{
    [Authorize(Roles = "admin")]
    public class RegionsController : Controller
    {
        private readonly AppCtx _context;

        public RegionsController(AppCtx context)
        {
            _context = context;
        }

        // GET: Regions
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["RegionSortParm"] = String.IsNullOrEmpty(sortOrder) ? "region_desc" : "";
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var regions = from r in _context.Regions
                           select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                regions = regions.Where(r => r.RegionName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "region_desc":
                    regions = regions.OrderByDescending(r => r.RegionName);
                    break;
                default:
                    regions = regions.OrderBy(r => r.RegionName);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Region>.CreateAsync(regions.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Regions/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Regions == null)
            {
                return NotFound();
            }

            var region = await _context.Regions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (region == null)
            {
                return NotFound();
            }

            return View(region);
        }

        // GET: Regions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Regions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRegionViewModel model)
        {
            if (_context.Regions
                .Where(f => f.RegionName == model.RegionName)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенная область уже существует");
            }

            if (ModelState.IsValid)
            {
                Region region = new()
                {
                    RegionName = model.RegionName
                };

                _context.Add(region);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Regions/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Regions == null)
            {
                return NotFound();
            }

            var region = await _context.Regions.FindAsync(id);
            if (region == null)
            {
                return NotFound();
            }

            EditRegionViewModel model = new()
            {
                Id = region.Id,
                RegionName = region.RegionName
            };
            return View(model);
        }

        // POST: Regions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditRegionViewModel model)
        {
            Region region = await _context.Regions.FindAsync(id);

            if (_context.Regions
                .Where(f => f.RegionName == model.RegionName)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенная область уже существует");
            }

            if (id != region.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    region.RegionName = model.RegionName;
                    _context.Update(region);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegionExists(region.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Regions/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.Regions == null)
            {
                return NotFound();
            }

            var region = await _context.Regions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (region == null)
            {
                return NotFound();
            }

            return View(region);
        }

        // POST: Regions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.Regions == null)
            {
                return Problem("Entity set 'AppCtx.Regions'  is null.");
            }
            var region = await _context.Regions.FindAsync(id);
            if (region != null)
            {
                _context.Regions.Remove(region);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegionExists(short id)
        {
          return (_context.Regions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

nedv/Views/Regions/Create.cshtml
@model nedv.ViewModel.Regions.CreateRegionViewModel

@{
    ViewData["Title"] = "Создание - Области";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Regions" asp-action="Index">Области</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление области
</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="RegionName" class="control-label"></label>
                <input asp-for="RegionName" class="form-control" />
                <span asp-validation-for="RegionName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nedv/Views/Regions/Delete.cshtml
@model nedv.Models.Data.Region

@{
    ViewData["Title"] = "Удаление - Области";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Regions" asp-action="Index">Области</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление области
</h3>

<h3>Вы уверены что хотите удалить?</h3>
<div>
    <h4>Область</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegionName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    </form>
</div>

nedv/Views/Regions/Details.cshtml
@model nedv.Models.Data.Region

@{
    ViewData["Title"] = "Просмотр - Области";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Regions" asp-action="Index">Области</a></li>
        <li class="breadcrumb-item active">Детали</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Просмотр области
</h3>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegionName)
        </dd>
    </dl>
</div>

nedv/Views/Regions/Edit.cshtml
@model nedv.ViewModel.Regions.EditRegionViewModel

@{
    ViewData["Title"] = "Изменение - Области";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Regions" asp-action="Index">Области</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение области
</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="mb-3">
                <label asp-for="RegionName" class="control-label"></label>
                <input asp-for="RegionName" class="form-control" />
                <span asp-validation-for="RegionName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nedv/Views/Regions/Index.cshtml
@model PaginatedList<nedv.Models.Data.Region>

@{
    ViewData["Title"] = "Области";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item active">Области</li>
    </ol>
</nav>
<h2>Области</h2>

<h6>
    <a class="btn text-dark" asp-action="Create">
        <i class="far fa-plus-square"></i>  Добавить область
    </a>
</h6>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Поиск по названию: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Поиск" class="btn btn-default" /> |
            <a asp-action="Index">Вернуться к списку</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["RegionSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Область</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegionName)
            </td>
            <td>
                    <a class="btn text-dark" asp-action="Details" asp-route-id="@item.Id" title="Посмотреть подробнее">
                        <i class="far fa-eye"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Edit" asp-route-id="@item.Id" title="Редактировать">
                        <i class="fas fa-pencil-alt"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Delete" asp-route-id="@item.Id" title="Удалить">
                        <i class="far fa-minus-square"></i>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>