nedv/Models/Data/Apartment.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace nedv.Models.Data
{
    public class Apartment
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public short Id { get; set; }

        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Display(Name = "Количество комнат")]
        public short CountRoom { get; set; }

        [Display(Name = "Количество метров квадратных")]
        public short NumberOfSquareMeters { get; set; }

        [Display(Name = "Этаж")]
        public short Floor { get; set; }

        [Display(Name = "Изображение")]
        public string? ImgUrl { get; set; }

        [Required(ErrorMessage = "Поле 'Изображение' обязательно для заполнения")]
        [NotMapped]
        [Display(Name = "Загрузить изображение")]
        public IFormFile ImageFile { get; set; }


        [Required]
        [Display(Name = "Тип объявления")]
        public short IdAdType { get; set; }

        [Required]
        [Display(Name = "Тип постройки")]
        public short IdTypeOfConstruction { get; set; }

        [Required]
        [Display(Name = "Город")]
        public short IdCity { get; set; }

        [Required]
        [Display(Name = "Пользователь")]
        public string IdUser { get; set; }

        //НАВИГАЦИОННЫЕ СВОЙСТВА

        //тип объявления
        [ForeignKey("IdAdType")]
        [Display(Name = "Тип объявления")]
        public AdType AdType { get; set; }

        //тип застройки
        [ForeignKey("IdTypeOfConstruction")]
        [Display(Name = "Тип застройки")]
        public TypeOfConstruction TypeOfConstruction { get; set; }

        //Город
        [ForeignKey("IdCity")]
        [Display(Name = "Город")]
        public City City { get; set; }

        //Пользователь
        [ForeignKey("IdUser")]
        [Display(Name = "Пользователь")]
        public User User { get; set; }
    }
}

nedv/Controllers/ApartmentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client.Extensions.Msal;
using nedv.Models;
using nedv.Models.Data;
using nedv.ViewModel.Apartment;

namespace nedv.Controllers
{
    [Authorize(Roles = "admin, registeredUser")]
    public class ApartmentsController : Controller
    {
        private readonly AppCtx _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ApartmentsController(AppCtx context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Apartments
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber, int? adtypeId)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DescriptionSortParam"] = String.IsNullOrEmpty(sortOrder) ? "description_desc" : "";
            ViewData["CountRoomSortParam"] = sortOrder == "countroom" ? "countroom_desc" : "countroom";
            ViewData["NumberOfSquareMetersSortParam"] = sortOrder == "numberofsquaremeters" ? "numberofsquaremeters_desc" : "numberofsquaremeters";
            ViewData["AdTypeSortParam"] = sortOrder == "adtype" ? "adtype_desc" : "adtype";
            ViewData["TypeOfConstructionSortParam"] = sortOrder == "typeofconstruction" ? "typeofconstruction_desc" : "typeofconstruction";
            ViewData["FloorSortParam"] = sortOrder == "floor" ? "floor_desc" : "floor";
            ViewData["CitySortParam"] = sortOrder == "city" ? "city_desc" : "city";
            ViewData["UserSortParam"] = String.IsNullOrEmpty(sortOrder) ? "user_desc" : "";

            ViewData["IdAdType"] =  adtypeId;
            ViewBag.AdTypes = _context.AdTypes.ToList();
           /* List<SelectListItem> selectList = new List<SelectListItem>
            {

            };*/

            var announcement = from a in _context.Apartments.Include(i => i.AdType).Include(i => i.TypeOfConstruction).Include(i => i.City).Include(i => i.User)
                               select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                announcement = announcement.Where(a => a.Description.Contains(searchString));
            }

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (adtypeId.HasValue)
            {
                announcement = announcement.Where(w => w.IdAdType == adtypeId.Value);
            }

            /*switch (sortOrder)
            {
                case "countroom":
                    announcement = announcement.OrderBy(a => a.CountRoom);
                    break;
                case "countroom_desc":
                    announcement = announcement.OrderByDescending(a => a.CountRoom);
                    break;
                case "numberofsquaremeters":
                    announcement = announcement.OrderBy(a => a.NumberOfSquareMeters);
                    break;
                case "numberofsquaremeters_desc":
                    announcement = announcement.OrderByDescending(a => a.NumberOfSquareMeters);
                    break;
                case "adtype":
                    announcement = announcement.OrderBy(a => a.AdType);
                    break;
                case "adtype_desc":
                    announcement = announcement.OrderByDescending(a => a.AdType);
                    break;
                case "typeofconstruction":
                    announcement = announcement.OrderBy(a => a.TypeOfConstruction);
                    break;
                case "typeofconstruction_desc":
                    announcement = announcement.OrderByDescending(a => a.TypeOfConstruction);
                    break;
                case "floor":
                    announcement = announcement.OrderBy(a => a.Floor);
                    break;
                case "floor_desc":
                    announcement = announcement.OrderByDescending(a => a.Floor);
                    break;
                case "city":
                    announcement = announcement.OrderBy(a => a.City);
                    break;
                case "city_desc":
                    announcement = announcement.OrderByDescending(a => a.City);
                    break;
                case "user_desc":
                    announcement = announcement.OrderByDescending(a => a.User);
                    break;
                default:
                    announcement = announcement.OrderBy(a => a.Description);
                    break;
            }*/

            int pageSize = 5;
            return View(await PaginatedList<Apartment>.CreateAsync(announcement.AsNoTracking(), pageNumber ?? 1, pageSize));
            /*var appCtx = _context.Apartments
                .Include(a => a.City)
                .Include(a => a.TypeOfConstruction)
                .Include(a => a.AdType)
                .Include(a => a.User);
            return View(await appCtx.ToListAsync()); */

        }

        // GET: Apartments/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Apartments == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartments
                .Include(a => a.City)
                .Include(a => a.TypeOfConstruction)
                .Include(a => a.User)
                .Include(a => a.AdType)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (apartment == null)
            {
                return NotFound();
            }

            return View(apartment);
        }

        // GET: Apartments/Create
        public IActionResult CreateAsync()
        {
            ViewData["IdCity"] = new SelectList(_context.Cities, "Id", "CityName");
            ViewData["IdTypeOfConstruction"] = new SelectList(_context.TypeOfConstructions, "Id", "TypeOfConstructionName");
            ViewData["IdUser"] = new SelectList(_context.Users, "Id", "Name", "Surname");
            ViewData["IdAdType"] = new SelectList(_context.AdTypes, "Id", "AdTypeName");
            return View();
        }

        // POST: Apartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateApartmentViewModel model)
        {
            if (_context.Apartments
                .Where(
                    f => f.IdCity == model.IdCity &&
                    f.IdUser == model.IdUser &&
                    f.IdAdType == model.IdAdType &&
                    f.IdTypeOfConstruction == model.IdTypeOfConstruction &&
                    f.Floor == model.Floor &&
                    f.NumberOfSquareMeters == model.NumberOfSquareMeters)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенное объявление уже существует");
            }

            if (ModelState.IsValid)
            {
                if  (model.ImageFile != null)
                {
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImageFile.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.ImgUrl = "/images/" + uniqueFileName;

                    using(var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await model.ImageFile.CopyToAsync(fileStream);
                    }

                }
                Apartment apartment = new()
                {
                    Description = model.Description,
                    CountRoom = model.CountRoom,
                    NumberOfSquareMeters = model.NumberOfSquareMeters,
                    ImgUrl = model.ImgUrl,
                    IdCity = model.IdCity,
                    IdUser = model.IdUser,
                    IdAdType = model.IdAdType,
                    IdTypeOfConstruction = model.IdTypeOfConstruction,
                    Floor = model.Floor,
                };

                _context.Add(apartment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound(ModelState);
            }

            return View(model);
        }

        // GET: Apartments/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Apartments == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartments.FindAsync(id);
            if (apartment == null)
            {
                return NotFound();
            }



            EditApartmentViewModel model = new()
            {
                Id = apartment.Id,
                IdCity = apartment.IdCity,
                Description = apartment.Description,
                CountRoom = apartment.CountRoom,
                NumberOfSquareMeters = apartment.NumberOfSquareMeters,
                ImgUrl = apartment.ImgUrl,
                Floor = apartment.Floor,
                IdAdType = apartment.IdAdType,
                IdTypeOfConstruction = apartment.IdTypeOfConstruction,
                IdUser = apartment.IdUser
            };

            ViewData["IdCity"] = new SelectList(_context.Cities, "Id", "CityName", apartment.IdCity);

nedv/Views/Apartments/Create.cshtml
@model nedv.ViewModel.Apartment.CreateApartmentViewModel

@{
    ViewData["Title"] = "Create";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Apartments" asp-action="Index">Объявления</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление объявления
</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="CountRoom" class="control-label"></label>
                <input asp-for="CountRoom" class="form-control" />
                <span asp-validation-for="CountRoom" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="NumberOfSquareMeters" class="control-label"></label>
                <input asp-for="NumberOfSquareMeters" class="form-control" />
                <span asp-validation-for="NumberOfSquareMeters" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ImageFile" class="control-label"></label>
                <input type="file" asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="IdAdType" class="control-label"></label>
                <select asp-for="IdAdType" class="form-control" asp-items="ViewBag.IdAdType"></select>
            </div>
            <div class="mb-3">
                <label asp-for="IdTypeOfConstruction" class="control-label"></label>
                <select asp-for="IdTypeOfConstruction" class ="form-control" asp-items="ViewBag.IdTypeOfConstruction"></select>
            </div>
            <div class="mb-3">
                <label asp-for="IdCity" class="control-label"></label>
                <select asp-for="IdCity" class ="form-control" asp-items="ViewBag.IdCity"></select>
            </div>
            <div class="mb-3">
                <label asp-for="IdUser" class="control-label"></label>
                <select asp-for="IdUser" class ="form-control" asp-items="ViewBag.IdUser"></select>
            </div>
            <div class="mb-3">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nedv/Views/Apartments/Delete.cshtml
@model nedv.Models.Data.Apartment

@{
    ViewData["Title"] = "Удаление";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Apartments" asp-action="Index">Объявления</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление объявления
</h3>
<div>
    <h4>Объявление</h4>
    <hr />
<div class="details_img_description">
    <img class="details_img" src="@Html.DisplayFor(model => model.ImgUrl)" alt="Image 1">
    <div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CountRoom)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CountRoom)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.NumberOfSquareMeters)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.NumberOfSquareMeters)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Floor)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Floor)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AdType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AdType.AdTypeName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TypeOfConstruction)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TypeOfConstruction.TypeOfConstructionName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City.CityName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.User)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.User.Name)
            </dd>
        </dl>
    </div>
</div>
    <br />
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

nedv/Views/Apartments/Details.cshtml
@model nedv.Models.Data.Apartment

@{
    ViewData["Title"] = "Details";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Apartments" asp-action="Index">Объявления</a></li>
        <li class="breadcrumb-item active">Детали</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Просмотр объявления
</h3>
<h4>Объявление</h4>
<div class="details_img_description">
    <img class="details_img" src="@Html.DisplayFor(model => model.ImgUrl)" alt="Image 1">
    <div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CountRoom)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CountRoom)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.NumberOfSquareMeters)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.NumberOfSquareMeters)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Floor)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Floor)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AdType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AdType.AdTypeName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TypeOfConstruction)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TypeOfConstruction.TypeOfConstructionName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City.CityName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.User)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.User.FullName)
            </dd>
        </dl>
    </div>
</div>

nedv/Views/Apartments/Edit.cshtml
@model nedv.ViewModel.Apartment.EditApartmentViewModel

@{
    ViewData["Title"] = "Edit";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Apartments" asp-action="Index">Объявления</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение объявления
</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="CountRoom" class="control-label"></label>
                <input asp-for="CountRoom" class="form-control" />
                <span asp-validation-for="CountRoom" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="NumberOfSquareMeters" class="control-label"></label>
                <input asp-for="NumberOfSquareMeters" class="form-control" />
                <span asp-validation-for="NumberOfSquareMeters" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ImageFile" class="control-label"></label>
                <input type="file" asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="IdAdType" class="control-label"></label>
                <select asp-for="IdAdType" class="form-control" asp-items="ViewBag.IdAdType"></select>
                <span asp-validation-for="IdAdType" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="IdTypeOfConstruction" class="control-label"></label>
                <select asp-for="IdTypeOfConstruction" class="form-control" asp-items="ViewBag.IdTypeOfConstruction"></select>
                <span asp-validation-for="IdTypeOfConstruction" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="IdCity" class="control-label"></label>
                <select asp-for="IdCity" class="form-control" asp-items="ViewBag.IdCity"></select>
                <span asp-validation-for="IdCity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="IdUser" class="control-label"></label>
                <select asp-for="IdUser" class="form-control" asp-items="ViewBag.IdUser"></select>
                <span asp-validation-for="IdUser" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}